#!/bin/bash
# Build LaTeX templates.
#
# Output is loaded at runtime via `loadScript('/lib/latex-templates.js')`
# in src/hooks/useLatexEngine.ts, which Vite serves from public/. There
# is no JS/TS code that imports this file directly. We previously also
# wrote a copy to src/lib/, but nothing read it — it was a parallel
# stale file that drifted easily and confused docs. Removed.

# Build to a temp file first, then copy to the canonical public/ location.
OUTPUT_PUBLIC="public/lib/latex-templates.js"
OUTPUT="/tmp/latex-templates.js"

echo "/**" > "$OUTPUT"
echo " * LaTeX Templates for SwiftLaTeX Browser Compilation" >> "$OUTPUT"
echo " * Auto-generated by build-templates.sh - DO NOT EDIT" >> "$OUTPUT"
echo " *" >> "$OUTPUT"
echo " * Output is deterministic — same tex/ input always produces the" >> "$OUTPUT"
echo " * same bundle. (No timestamp etc., so the bundle-sync CI check" >> "$OUTPUT"
echo " * in test.yml can use a simple \`git diff --exit-code\`. Use" >> "$OUTPUT"
echo " * \`git log public/lib/latex-templates.js\` to see when it was last" >> "$OUTPUT"
echo " * regenerated.)" >> "$OUTPUT"
echo " */" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "const LATEX_TEMPLATES = {" >> "$OUTPUT"

# Add main.tex from tex/
echo "  'tex/main.tex': \`" >> "$OUTPUT"
cat tex/main.tex | sed 's/\\/\\\\/g' | sed 's/\`/\\\`/g' | sed 's/\$/\\$/g' >> "$OUTPUT"
echo "\`," >> "$OUTPUT"

# Add template files from tex/templates/
echo "" >> "$OUTPUT"
echo "  // Template files" >> "$OUTPUT"
for file in tex/templates/*.tex; do
    name=$(basename "$file")
    echo "  'tex/templates/$name': \`" >> "$OUTPUT"
    cat "$file" | sed 's/\\/\\\\/g' | sed 's/\`/\\\`/g' | sed 's/\$/\\$/g' >> "$OUTPUT"
    echo "\`," >> "$OUTPUT"
done

echo "};" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "// Export for use in app.js" >> "$OUTPUT"
echo "if (typeof window !== 'undefined') {" >> "$OUTPUT"
echo "  window.LATEX_TEMPLATES = LATEX_TEMPLATES;" >> "$OUTPUT"
echo "}" >> "$OUTPUT"

cp "$OUTPUT" "$OUTPUT_PUBLIC"

echo "Generated $OUTPUT_PUBLIC"
