import { escapeLatex, escapeLatexUrl, processBodyText, formatSubjectForLatex, formatAddressForLatex } from './escaper';
import type { DocumentData, Reference, Enclosure, Paragraph, CopyTo, Distribution } from '@/types/document';
import { DOC_TYPE_CONFIG } from '@/types/document';
import { base64ToUint8Array } from '@/lib/encoding';

interface DocumentStore {
  docType: string;
  formData: Partial<DocumentData>;
  references: Reference[];
  enclosures: Enclosure[];
  paragraphs: Paragraph[];
  copyTos: CopyTo[];
  distributions: Distribution[];
}

// const PARAGRAPH_INDENT_SPACES = 4; // Used in getBodyText for plain text output

function getParagraphLabel(level: number, count: number): string {
  const patterns = [
    (n: number) => `${n}.`,
    (n: number) => `${String.fromCharCode(96 + n)}.`,
    (n: number) => `(${n})`,
    (n: number) => `(${String.fromCharCode(96 + n)})`,
  ];
  const pattern = patterns[level % 4];
  return pattern(count);
}

function calculateLabels(paragraphs: Paragraph[]): string[] {
  const labels: string[] = [];
  const counters = [0, 0, 0, 0, 0, 0, 0, 0];

  for (const para of paragraphs) {
    for (let i = para.level + 1; i < 8; i++) {
      counters[i] = 0;
    }
    counters[para.level]++;
    labels.push(getParagraphLabel(para.level, counters[para.level]));
  }

  return labels;
}

// getBodyText is used for plain text output (not LaTeX)
// Keeping for potential future use in exports
// function getBodyText(paragraphs: Paragraph[]): string {
//   const labels = calculateLabels(paragraphs);
//   return paragraphs
//     .map((para, i) => {
//       const indent = ' '.repeat(para.level * PARAGRAPH_INDENT_SPACES);
//       return `${indent}${labels[i]}  ${para.text}`;
//     })
//     .join('\n\n');
// }

export function generateDocumentTex(store: DocumentStore): string {
  const data = store.formData;
  // config will be used for document-type specific variations
  const config = DOC_TYPE_CONFIG[store.docType] || DOC_TYPE_CONFIG.naval_letter;
  const isMOAMode = config.uiMode === 'moa';
  const isJointMode = config.uiMode === 'joint' || config.uiMode === 'joint_memo';
  const isExecutiveMode = config.uiMode === 'executive';

  let tex = `%=============================================================================
% DOCUMENT CONFIGURATION - Generated by dondocs
%=============================================================================

\\setDocumentType{${store.docType}}
\\setFontSize{${data.fontSize || '12pt'}}
\\setFontFamily{${data.fontFamily || 'times'}}
\\setPageNumberStyle{${data.pageNumbering || 'none'}}

`;

  // For MOA/MOU: document-level SSIC/Serial/Date = Senior command values
  // For Joint Letter/Memo: document-level SSIC/Serial/Date used for Senior side
  //   in the template's \printDateAndTitle (joint_letter.tex uses \DocumentSSIC etc,
  //   joint_memorandum.tex uses \DocumentDate)
  const ssic = isMOAMode ? data.seniorSSIC : data.ssic;
  const serial = isMOAMode ? data.seniorSerial : data.serial;
  const docDate = isMOAMode ? data.seniorDate : data.date;

  // For business letters and executive correspondence, set BusinessDate,
  // BusinessRecipientAddress, etc. Both use the same template address/salutation pattern.
  const isBusinessLetter = config.uiMode === 'business';

  // Joint letter and joint memo share the same joint* fields
  const fromLine = isJointMode ? data.jointSeniorFrom : data.from;
  const toLine = isJointMode ? data.jointTo : data.to;
  // Subject line casing per SECNAV M-5216.5:
  //   Executive types (Ch 12 ¶2l): Title Case (NOT ALL CAPS)
  //   This applies to all executive uiMode types AND executive_correspondence
  //   All other types: ALL CAPS
  // Also wrap at 57 characters per SECNAV formatting requirements
  const rawSubject = isJointMode ? data.jointSubject : (isMOAMode ? data.moaSubject : data.subject);
  const usesTitleCaseSubject = isExecutiveMode || store.docType === 'executive_correspondence';
  const subjectLine = usesTitleCaseSubject
    ? formatSubjectForLatex(toTitleCase(rawSubject || ''))
    : formatSubjectForLatex(rawSubject?.toUpperCase());

  tex += `\\setSSIC{${config.ssic ? escapeLatex(ssic) : ''}}
\\setSerial{${config.ssic ? escapeLatex(serial) : ''}}
\\setDocumentDate{${escapeLatex(docDate)}}
${isBusinessLetter ? `\\setBusinessDate{${escapeLatex(docDate)}}` : '% Not a business letter'}

${data.inReplyTo ? `\\enableInReplyReferTo
\\setInReplyReferTo{${escapeLatex(data.inReplyToText)}}` : '% No In Reply Refer To'}

\\setFrom
    {${formatAddressForLatex(fromLine)}}
    {}{}{}

${isBusinessLetter ? `% Business letter: format recipient address as block with line breaks
% Split by newlines (handle both \\n and \\r\\n), escape each line, join with \\\\
\\setBusinessRecipientAddress{${
  (toLine || '')
    .split(/\r?\n/)
    .filter(line => line.trim())
    .map(line => escapeLatex(line.trim()))
    .join('\\\\\n')
}}` : `\\setTo
    {${formatAddressForLatex(toLine)}}
    {}{}{}{}`}

${data.via?.trim() ? (() => {
  // Split once and pad to 4 lines so indices 0..3 are always defined.
  // Previously this called data.via?.split('\n')[N] four separate times and
  // leaned on `|| ''` to paper over undefined entries — fragile and wasted
  // work (see #20). Empty strings are rendered as empty LaTeX groups.
  const viaLines = data.via.split('\n');
  const [l0 = '', l1 = '', l2 = '', l3 = ''] = viaLines;
  return `\\setVia
    {${escapeLatex(l0)}}
    {${escapeLatex(l1)}}
    {${escapeLatex(l2)}}
    {${escapeLatex(l3)}}`;
})() : '% No Via'}

\\setSubject{${subjectLine}}
${data.showSubjectOnContinuation ? `\\setContinuationSubject{${subjectLine}}` : '% Continuation subject disabled'}

\\setBusinessSalutation{${escapeLatex((data.salutation || 'Dear Sir or Madam:').trim())}}
\\setBusinessClose{${escapeLatex(data.complimentaryClose || 'Sincerely,')}}

\\setPOC{${escapeLatex(data.pocEmail)}}
`;

  // Memorandum For: addressee is embedded in the title ("MEMORANDUM FOR [addressee]")
  // The 'to' field holds the addressee text (e.g., "All Department Heads")
  if (store.docType === 'mf' && data.to) {
    tex += `\\setMemorandumForAddressee{${escapeLatex(data.to)}}\n`;
  }

  // Executive memo fields (standard_memorandum, action_memorandum, information_memorandum)
  // Each template defines its own commands — set the ones it expects
  if (isExecutiveMode) {
    // Standard memo + Action memo: \setMemorandumForAddressee
    if (store.docType === 'standard_memorandum' || store.docType === 'action_memorandum') {
      tex += `\\setMemorandumForAddressee{${escapeLatex(data.memorandumFor)}}\n`;
    }

    // Action memo: \setActionFrom (FROM line in address block)
    if (store.docType === 'action_memorandum') {
      tex += `\\setActionFrom{${escapeLatex(data.from)}}\n`;
    }

    // Information memo: \setInfoMemoFor, \setInfoMemoFrom, \setInfoMemoCoordination, \setInfoMemoPreparedBy
    if (store.docType === 'information_memorandum') {
      tex += `\\setInfoMemoFor{${escapeLatex(data.memorandumFor)}}\n`;
      tex += `\\setInfoMemoFrom{${escapeLatex(data.from)}}\n`;
      if (data.coordination) {
        tex += `\\setInfoMemoCoordination{${escapeLatex(data.coordination)}}\n`;
      }
      if (data.preparedBy) {
        tex += `\\setInfoMemoPreparedBy{${escapeLatex(data.preparedBy)}}\n`;
      }
    }

    // Action memo coordination/preparedBy — these aren't in the current .tex template
    // but could be added later; for now the body handles them via ParagraphsEditor
  }

  // Endorsements: parse subject field to set EndorsementOrdinal and BasicLetterID
  // Subject contains the full endorsement line, e.g.:
  //   "FIRST ENDORSEMENT on LCpl T. M. Garcia's Special Liberty Request of 20 Jan 26"
  if (store.docType === 'same_page_endorsement' || store.docType === 'new_page_endorsement') {
    const subjectText = data.subject || '';
    // Try to parse "ORDINAL ENDORSEMENT on BASIC_LETTER_ID"
    const endorsementMatch = subjectText.match(/^(.+?)\s+ENDORSEMENT(?:\s+on\s+(.+))?$/i);
    if (endorsementMatch) {
      const ordinal = endorsementMatch[1].trim();
      const basicLetterId = endorsementMatch[2]?.trim() || '';
      // Both types: set ordinal and basic letter ID
      tex += `\\renewcommand{\\EndorsementOrdinal}{${escapeLatex(ordinal)}}\n`;
      if (basicLetterId) {
        tex += `\\renewcommand{\\BasicLetterID}{${escapeLatex(basicLetterId)}}\n`;
      }
    }
    // Always set serial and date for same-page endorsement, regardless of subject match
    if (store.docType === 'same_page_endorsement') {
      tex += `\\renewcommand{\\EndorsementSerial}{${escapeLatex(data.serial || '')}}\n`;
      tex += `\\renewcommand{\\EndorsementDate}{${escapeLatex(data.date || '')}}\n`;
    }
  }

  return tex;
}

export function generateLetterheadTex(store: DocumentStore): string {
  const data = store.formData;

  // Parse address: format is "Street/Box, City, State ZIP" (comma-separated)
  // Only split into two lines when there are 2+ commas (street + city/state).
  // A single comma like "PRESIDIO OF MONTEREY, CA 93944" stays on one line.
  const rawAddress = (data.unitAddress || '').trim();
  const commaCount = (rawAddress.match(/,/g) || []).length;
  let addressLine1: string;
  let addressLine2: string;
  if (commaCount >= 2) {
    const firstComma = rawAddress.indexOf(',');
    addressLine1 = rawAddress.slice(0, firstComma).trim();
    addressLine2 = rawAddress.slice(firstComma + 1).trim();
  } else {
    addressLine1 = rawAddress;
    addressLine2 = '';
  }

  // Check if unit line 2 has content
  const hasLine2 = !!data.unitLine2?.trim();

  // When line 2 is empty, shift content up to eliminate the gap
  // Line 2 empty: UnitName, Address1, Address2, (empty)
  // Line 2 has content: UnitName, UnitLine2, Address1, Address2
  const line1 = escapeLatex(data.unitLine1);
  const line2 = hasLine2 ? escapeLatex(data.unitLine2) : escapeLatex(addressLine1);
  const line3 = hasLine2 ? escapeLatex(addressLine1) : escapeLatex(addressLine2);
  const line4 = hasLine2 ? escapeLatex(addressLine2) : '';

  return `%=============================================================================
% LETTERHEAD CONFIGURATION - Generated by dondocs
% Per SECNAV M-5216.5: Unit name, address
%=============================================================================

% Seal type: dow (Department of War) or dod (Department of Defense)
\\setSealType{${data.sealType || 'dow'}}

% Department/Service: usmc, navy, or dod
\\setDepartment{${data.department || 'usmc'}}

% Letterhead color: blue (default) or black
\\setLetterheadColor{${data.letterheadColor || 'blue'}}

\\setLetterhead
    {${line1}}
    {${line2}}
    {${line3}}
    {${line4}}
`;
}

// Capitalize first letter of each word
function capitalizeWord(word: string | undefined): string {
  if (!word) return '';
  return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
}

export function generateSignatoryTex(store: DocumentStore): string {
  const data = store.formData;
  const config = DOC_TYPE_CONFIG[store.docType] || DOC_TYPE_CONFIG.naval_letter;

  // Check if this is a dual-signature document (MOA/MOU)
  if (config.uiMode === 'moa') {
    return generateMOASignatoryTex(store);
  }

  // Check if this is a joint letter or joint memorandum (dual letterheads and signatures)
  if (config.uiMode === 'joint' || config.uiMode === 'joint_memo') {
    return generateJointLetterSignatoryTex(store);
  }

  // Properly capitalize names: First Middle LAST
  const firstName = capitalizeWord(data.sigFirst);
  const middleName = capitalizeWord(data.sigMiddle);
  const lastName = data.sigLast?.toUpperCase() || '';

  const fullName = [firstName, middleName, lastName]
    .filter(Boolean)
    .join(' ');

  // Abbreviated format: F. M. LASTNAME
  const abbrevName = [
    firstName ? `${firstName[0].toUpperCase()}.` : '',
    middleName ? `${middleName[0].toUpperCase()}.` : '',
    lastName,
  ]
    .filter(Boolean)
    .join(' ');

  let byDirectionTex = '';
  if (data.byDirection) {
    const authority = data.byDirectionAuthority || 'the Commanding Officer';
    byDirectionTex = `\\setByDirection{By direction of ${escapeLatex(authority)}}`;
  }

  // Set signature type and image
  // signatureType: 'none' = just typed name, 'image' = uploaded signature, 'digital' = empty field for CAC signing
  const signatureType = data.signatureType || 'none';
  let signatureConfigTex = '';

  if (signatureType === 'image' && data.signatureImage?.data) {
    // Use uploaded signature image
    signatureConfigTex = '\\setSignatureImage{signature.png}';
  } else if (signatureType === 'digital') {
    // Create empty digital signature field
    signatureConfigTex = '\\setDigitalSignatureField';
  } else {
    // No signature image or field
    signatureConfigTex = '\\setSignatureImage{}';
  }

  return `%=============================================================================
% SIGNATURE CONFIGURATION - Generated by dondocs
%=============================================================================

\\setSignatory
    {${escapeLatex(firstName)}}
    {${escapeLatex(middleName)}}
    {${escapeLatex(lastName)}}
    {${escapeLatex(data.sigRank)}}
    {${escapeLatex(data.sigTitle)}}

\\setSignatoryName{${escapeLatex(fullName)}}
\\setSignatoryAbbrev{${escapeLatex(abbrevName)}}

${byDirectionTex}

${signatureConfigTex}
`;
}

// Generate MOA/MOU specific signatory configuration (dual signatures)
// Uses ONLY commands that exist in the original cached template
function generateMOASignatoryTex(store: DocumentStore): string {
  const data = store.formData;
  const signatureType = data.signatureType || 'none';

  // Digital signature field for dual signatures
  let signatureConfigTex = '';
  if (signatureType === 'digital') {
    signatureConfigTex = '\\setDigitalSignatureField';
  }

  // Senior signatory name formatting (same as standard signatory).
  // Split once and read first/last word safely (see #20). When the input
  // has a single word or is empty, `first` === `last` === that word (or
  // empty string), which is the same behavior the old `?.split(...)[0]` /
  // `?.slice(-1)[0] || ''` chain produced but without the repeated splits
  // or the implicit-undefined pitfalls.
  const seniorFullName = data.seniorSigName || '';
  const seniorParts = seniorFullName.split(' ').filter(Boolean);
  const seniorFirstName = capitalizeWord(seniorParts[0]);
  const seniorLastName = (seniorParts[seniorParts.length - 1] || '').toUpperCase();
  const seniorAbbrev = seniorFirstName ? `${seniorFirstName[0]}. ${seniorLastName}` : seniorLastName;

  // Junior signatory name formatting (abbreviated like senior: "R. CHIOFALO")
  const juniorFullName = data.juniorSigName || '';
  const juniorParts = juniorFullName.split(' ').filter(Boolean);
  const juniorFirstName = capitalizeWord(juniorParts[0]);
  const juniorLastName = (juniorParts[juniorParts.length - 1] || '').toUpperCase();
  const juniorAbbrev = juniorFirstName ? `${juniorFirstName[0]}. ${juniorLastName}` : juniorLastName;

  // Use EXISTING commands only - Senior uses document-level fields + standard signatory
  // Junior uses Junior-prefixed fields (which already exist)
  return `%=============================================================================
% MOA/MOU DUAL SIGNATURE CONFIGURATION - Generated by dondocs
%=============================================================================

% Senior Command (Signs Last - Right Side)
% Uses SeniorCommandName (exists) + document-level SSIC/Serial/Date + standard signatory
\\renewcommand{\\SeniorCommandName}{${escapeLatex(data.seniorCommandName)}}

% Senior signatory uses standard signatory fields
\\setSignatory
    {${escapeLatex(seniorFirstName)}}
    {}
    {${escapeLatex(seniorLastName)}}
    {${escapeLatex(data.seniorSigRank)}}
    {${escapeLatex(data.seniorSigTitle)}}
\\setSignatoryName{${escapeLatex(seniorFullName)}}
\\setSignatoryAbbrev{${escapeLatex(seniorAbbrev)}}

% Junior Command (Signs First - Left Side) - uses Junior-prefixed fields
\\renewcommand{\\JuniorCommandName}{${escapeLatex(data.juniorCommandName)}}
\\renewcommand{\\JuniorSSIC}{${escapeLatex(data.juniorSSIC)}}
\\renewcommand{\\JuniorSerial}{${escapeLatex(data.juniorSerial)}}
\\renewcommand{\\JuniorDate}{${escapeLatex(data.juniorDate)}}
\\renewcommand{\\JuniorSignatoryName}{${escapeLatex(juniorAbbrev)}}
\\renewcommand{\\JuniorSignatoryRank}{${escapeLatex(data.juniorSigRank)}}
\\renewcommand{\\JuniorSignatoryTitle}{${escapeLatex(data.juniorSigTitle)}}

${signatureConfigTex}
`;
}

// Generate Joint Letter / Joint Memorandum specific configuration
// Both use the same joint* fields (shared UI) — only the designation text differs
function generateJointLetterSignatoryTex(store: DocumentStore): string {
  const data = store.formData;
  const signatureType = data.signatureType || 'none';

  // Digital signature field for dual signatures
  let signatureConfigTex = '';
  if (signatureType === 'digital') {
    signatureConfigTex = '\\setDigitalSignatureField';
  }

  // Parse senior signatory name (format: "J. A. SMITH" -> "J. A." first, "SMITH" last)
  const seniorFullName = data.jointSeniorSigName || '';
  const seniorParts = seniorFullName.split(' ');
  const seniorLastName = seniorParts[seniorParts.length - 1]?.toUpperCase() || '';
  const seniorFirstInitials = seniorParts.slice(0, -1).join(' ');
  const seniorAbbrev = seniorFullName.toUpperCase();

  // Junior signatory name (used as full uppercase name)
  const juniorFullName = data.jointJuniorSigName || '';

  return `%=============================================================================
% JOINT DUAL CONFIGURATION - Generated by dondocs
% Per SECNAV M-5216.5 Ch 7, Para 7-1.2; Figure 7-4
%=============================================================================

% Senior Command (Right Side - Signs Last)
\\renewcommand{\\SeniorCommandName}{${escapeLatex(data.jointSeniorName)}}
\\renewcommand{\\SeniorCommandZip}{${escapeLatex(data.jointSeniorZip)}}
\\renewcommand{\\SeniorCommandCode}{${escapeLatex(data.jointSeniorCode)}}
\\renewcommand{\\SeniorFromLine}{${escapeLatex(data.jointSeniorFrom)}}

% Senior signatory uses standard signatory fields
\\setSignatory
    {${escapeLatex(seniorFirstInitials)}}
    {}
    {${escapeLatex(seniorLastName)}}
    {}
    {${escapeLatex(data.jointSeniorSigTitle)}}
\\setSignatoryName{${escapeLatex(seniorFullName)}}
\\setSignatoryAbbrev{${escapeLatex(seniorAbbrev)}}

% Junior Command (Left Side - Signs First)
\\renewcommand{\\JuniorCommandName}{${escapeLatex(data.jointJuniorName)}}
\\renewcommand{\\JuniorCommandZip}{${escapeLatex(data.jointJuniorZip)}}
\\renewcommand{\\JuniorCommandCode}{${escapeLatex(data.jointJuniorCode)}}
\\renewcommand{\\JuniorSSIC}{${escapeLatex(data.jointJuniorSSIC)}}
\\renewcommand{\\JuniorSerial}{${escapeLatex(data.jointJuniorSerial)}}
\\renewcommand{\\JuniorDate}{${escapeLatex(data.jointJuniorDate)}}
\\renewcommand{\\JuniorFromLine}{${escapeLatex(data.jointJuniorFrom)}}
\\renewcommand{\\JuniorSignatoryName}{${escapeLatex(juniorFullName.toUpperCase())}}
\\renewcommand{\\JuniorSignatoryTitle}{${escapeLatex(data.jointJuniorSigTitle)}}

% Common location (appears in letterhead)
\\renewcommand{\\CommonLocation}{${escapeLatex(data.jointCommonLocation)}}

${signatureConfigTex}
`;
}

export function generateFlagsTex(store: DocumentStore): string {
  let flags = '% Flags - Generated by dondocs\n';
  if (store.references.length > 0) {
    flags += '\\setHasReferences\n';
  }
  if (store.enclosures.length > 0) {
    flags += '\\setHasEnclosures\n';
  }
  if (store.formData.includeHyperlinks) {
    flags += '\\setHyperlinksEnabled\n';
  }
  return flags;
}

export function generateReferencesTex(store: DocumentStore): string {
  if (store.references.length === 0) {
    return '% No references\n';
  }

  return `%=============================================================================
% REFERENCES - Generated by dondocs
% Count: ${store.references.length} references
%=============================================================================

${store.references.map((r, i) => {
    const cmd = i === store.references.length - 1 ? '\\lastrefitem' : '\\refitem';
    return `${cmd}{${r.letter}}{${escapeLatex(r.title)}}`;
  }).join('\n')}
`;
}

export function generateReferenceUrlsTex(store: DocumentStore): string {
  const refsWithUrls = store.references.filter((r) => r.url?.trim());
  if (refsWithUrls.length === 0) return '% No reference URLs\n';

  return `%=============================================================================
% REFERENCE URLS - Generated by dondocs
%=============================================================================

${refsWithUrls.map((r) => `\\setRefURL{${r.letter}}{${escapeLatexUrl(r.url)}}`).join('\n')}
`;
}

export function generateEnclosuresTex(store: DocumentStore): string {
  if (store.enclosures.length === 0) {
    return '% No enclosures\n';
  }

  return `%=============================================================================
% ENCLOSURES - Generated by dondocs
% Count: ${store.enclosures.length} enclosures
%=============================================================================

${store.enclosures
    .map((e, i) => {
      // Always use JSPDF marker - JavaScript handles ALL enclosure pages
      // This ensures correct ordering (text-only and PDF enclosures in sequence)
      return `\\enclosure{${i + 1}}{JSPDF}{${escapeLatex(e.title || 'Untitled')}}`;
    })
    .join('\n')}
`;
}

export function generateCopyToTex(store: DocumentStore): string {
  if (store.copyTos.length === 0) {
    return '% No copy-to recipients\n';
  }

  // Build pre-built tabular rows: first row has "Copy to:" label, rest are continuation
  const rows = store.copyTos.map((ct, i) => {
    if (i === 0) {
      return `    Copy to:\\hspace{2\\fontdimen2\\font} & ${escapeLatex(ct.text)} \\\\`;
    }
    return `     & ${escapeLatex(ct.text)} \\\\`;
  });

  return `%=============================================================================
% COPY TO - Generated by dondocs
% Count: ${store.copyTos.length} recipients
%=============================================================================

\\setHasCopyTo
\\newcommand{\\CopyToRows}{%
${rows.join('\n')}
}
`;
}

export function generateDistributionTex(store: DocumentStore): string {
  if (!store.distributions || store.distributions.length === 0) {
    return '% No distribution recipients\n';
  }

  // Build pre-built tabular rows: first row has "Distribution:" label, rest are continuation
  const rows = store.distributions.map((d, i) => {
    if (i === 0) {
      return `    Distribution:\\hspace{2\\fontdimen2\\font} & ${escapeLatex(d.text)} \\\\`;
    }
    return `     & ${escapeLatex(d.text)} \\\\`;
  });

  return `%=============================================================================
% DISTRIBUTION - Generated by dondocs
% Count: ${store.distributions.length} recipients
%=============================================================================

\\setHasDistribution
\\newcommand{\\DistributionRows}{%
${rows.join('\n')}
}
`;
}

// Convert header to Title Case per SECNAV M-5216.5 Ch 7 ¶13d
function toTitleCase(str: string): string {
  // Words that should remain lowercase (unless first word)
  const lowercaseWords = ['a', 'an', 'and', 'as', 'at', 'but', 'by', 'for', 'in', 'nor', 'of', 'on', 'or', 'so', 'the', 'to', 'up', 'yet'];
  
  return str.split(' ').map((word, index) => {
    const lower = word.toLowerCase();
    // Always capitalize first word, otherwise check if it's a lowercase word
    if (index === 0 || !lowercaseWords.includes(lower)) {
      return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
    }
    return lower;
  }).join(' ');
}

/** Underline entire header text using ulem's \uline for proper positioning. */
function underlineWords(text: string): string {
  return `\\uline{${text}}`;
}

export function generateBodyTex(store: DocumentStore): string {
  const labels = calculateLabels(store.paragraphs);
  const config = DOC_TYPE_CONFIG[store.docType] || DOC_TYPE_CONFIG.naval_letter;

  // Business letters and endorsements don't use numbered paragraphs
  const useNumberedParagraphs = config.compliance.numberedParagraphs;
  // Business letters and executive correspondence use 0.5" first-line indent instead of numbers
  const isBusinessLetter = config.uiMode === 'business';

  // Build the body via array-push-then-join. The previous `latex += ...`
  // pattern inside the paragraph loop is O(n²) under naive implementations
  // (each += allocates a new string equal to the accumulated length).
  // Modern engines optimize this with rope strings, but the array form
  // is unambiguously linear and matches the pattern we use elsewhere.
  const parts: string[] = [
    `%=============================================================================
% DOCUMENT BODY - Generated by dondocs
% SECNAV M-5216.5 Ch 7 ¶13: "Do not indent the continuation lines of a subparagraph."
% Continuation lines return to the label position using \\leftskip
%=============================================================================

`,
  ];

  for (let i = 0; i < store.paragraphs.length; i++) {
    const para = store.paragraphs[i];
    const label = useNumberedParagraphs ? labels[i] : '';
    const headerText = para.header?.trim();

    if (para.level === 0) {
      // Level 0: Main paragraph with optional underlined header
      // Per SECNAV M-5216.5 Ch 7 ¶13d: "Underline any heading and capitalize its key words"
      if (isBusinessLetter) {
        // Business letter: 0.5" first-line indent, no numbers
        if (headerText) {
          const formattedHeader = toTitleCase(headerText);
          parts.push(`\\vspace{12pt}\n\\noindent\\hspace{0.5in}${underlineWords(escapeLatex(formattedHeader))}.  ${processBodyText(para.text)}\n\n`);
        } else {
          parts.push(`\\vspace{12pt}\n\\noindent\\hspace{0.5in}${processBodyText(para.text)}\n\n`);
        }
      } else if (headerText) {
        const formattedHeader = toTitleCase(headerText);
        parts.push(`\\vspace{12pt}\n\\noindent ${label} ${underlineWords(escapeLatex(formattedHeader))}.  ${processBodyText(para.text)}\n\n`);
      } else {
        parts.push(`\\vspace{12pt}\n\\noindent ${label}  ${processBodyText(para.text)}\n\n`);
      }
    } else {
      // Subparagraphs: Use leftskip for proper continuation line wrapping
      // Per SECNAV Ch 7 ¶13: continuation lines return to label position
      const levelIndent = isBusinessLetter ? (para.level + 1) * 0.5 : para.level * 0.25; // Business: 0.5" per level, Others: 0.25"

      if (headerText) {
        const formattedHeader = toTitleCase(headerText);
        parts.push(`\\vspace{6pt}\n{\\leftskip=${levelIndent}in\n\\noindent ${label} ${underlineWords(escapeLatex(formattedHeader))}. ${processBodyText(para.text)}\\par}\n\n`);
      } else {
        parts.push(`\\vspace{6pt}\n{\\leftskip=${levelIndent}in\n\\noindent ${label} ${processBodyText(para.text)}\\par}\n\n`);
      }
    }
  }

  return parts.join('');
}

export function generateClassificationTex(store: DocumentStore): string {
  const data = store.formData;

  if (data.classLevel === 'unclassified' || !data.classLevel) {
    return '% Unclassified - no classification markings\n';
  }

  if (data.classLevel === 'cui') {
    return `%=============================================================================
% CUI CONFIGURATION - Generated by dondocs
%=============================================================================

\\setCUI
\\setCUIControlledBy{${escapeLatex(data.cuiControlledBy)}}
\\setCUICategory{${escapeLatex(data.cuiCategory)}}
\\setCUIDissemination{${escapeLatex(data.cuiDissemination)}}
\\setCUIDistStatement{${escapeLatex(data.cuiDistStatement)}}
\\setPOC{${escapeLatex(data.pocEmail)}}
`;
  }

  // Handle custom classification - just output the text verbatim as banner only
  // Uses \setCustomClassification which sets banners but NOT the classified info block
  if (data.classLevel === 'custom' && data.customClassification) {
    return `%=============================================================================
% CUSTOM CLASSIFICATION - Generated by dondocs
%=============================================================================

\\setCustomClassification{${escapeLatex(data.customClassification)}}
`;
  }

  const classLevelMap: Record<string, string> = {
    confidential: 'CONFIDENTIAL',
    secret: 'SECRET',
    top_secret: 'TOP SECRET',
    top_secret_sci: 'TOP SECRET//SCI',
  };

  return `%=============================================================================
% CLASSIFICATION CONFIGURATION - Generated by dondocs
%=============================================================================

\\setClassification{${classLevelMap[data.classLevel] || 'SECRET'}}
\\setClassifiedBy{${escapeLatex(data.classifiedBy)}}
\\setDerivedFrom{${escapeLatex(data.derivedFrom)}}
\\setDeclassifyOn{${escapeLatex(data.declassifyOn)}}
\\setClassificationReason{${escapeLatex(data.classReason)}}
\\setPOC{${escapeLatex(data.classifiedPocEmail)}}
`;
}

export interface EnclosureData {
  number: number;
  title: string;
  data?: ArrayBuffer; // undefined = text-only enclosure (no PDF)
  pageStyle?: 'border' | 'fullpage' | 'fit';
  hasCoverPage?: boolean;
  coverPageDescription?: string;
}

export interface ReferenceUrlData {
  letter: string;
  url: string;
}

export interface GeneratedFiles {
  texFiles: Record<string, string>;
  enclosures: EnclosureData[];
  includeHyperlinks: boolean;
  signatureImage?: Uint8Array; // PNG data for signature image
  referenceUrls: ReferenceUrlData[]; // URLs for reference hyperlinks
}

export function generateAllLatexFiles(store: DocumentStore): GeneratedFiles {
  // Files are written to root level to match \input{} paths in latex-templates.js
  const texFiles: Record<string, string> = {
    'document.tex': generateDocumentTex(store),
    'letterhead.tex': generateLetterheadTex(store),
    'signatory.tex': generateSignatoryTex(store),
    'flags.tex': generateFlagsTex(store),
    'references.tex': generateReferencesTex(store),
    'reference-urls.tex': generateReferenceUrlsTex(store),
    'encl-config.tex': generateEnclosuresTex(store),
    'copyto-config.tex': generateCopyToTex(store),
    'distribution-config.tex': generateDistributionTex(store),
    'body.tex': generateBodyTex(store),
    'classification.tex': generateClassificationTex(store),
  };

  // Collect ALL enclosures for JavaScript handling (maintains correct order)
  const enclosures: EnclosureData[] = store.enclosures.map((encl, i) => ({
    number: i + 1,
    title: encl.title || 'Untitled',
    data: encl.file?.data, // undefined if no PDF attached
    pageStyle: encl.pageStyle,
    hasCoverPage: encl.hasCoverPage,
    coverPageDescription: encl.coverPageDescription,
  }));

  // Convert signature image from base64 to Uint8Array if present
  const signatureImage = store.formData.signatureImage?.data
    ? base64ToUint8Array(store.formData.signatureImage.data)
    : undefined;

  // Collect reference URLs for hyperlink creation
  const referenceUrls: ReferenceUrlData[] = store.references
    .filter((r) => r.url?.trim())
    .map((r) => ({ letter: r.letter, url: r.url! }));

  return { texFiles, enclosures, includeHyperlinks: !!store.formData.includeHyperlinks, signatureImage, referenceUrls };
}
